entries:
  - type: Heavy
    category: Beast
    melee:
      activation: 5
      to_hit_attacking: 3
      to_hit_defending: 6
    move:
      activation: 6
      Distance: 10
    fighting_strength:
      current: 6
      maximum: 6
    resolve: 3
    toughness: 4
    traits:
      - Reckless
    points: 6
  - type: Light
    category: Beast
    melee:
      activation: 5
      to_hit_attacking: 4
      to_hit_defending: 6
    move:
      activation: 6
      Distance: 12
    fighting_strength:
      current: 6
      maximum: 6
    resolve: 4
    toughness: 3
    traits:
      - Reckless
      - Nimble
    points: 4
  - type: Elite
    category: Cavalry
    melee:
      activation: 5
      to_hit_attacking: 3
      to_hit_defending: 5
    move:
      activation: 7
      Distance: 10
    fighting_strength:
      current: 6
      maximum: 6
    resolve: 3
    toughness: 4
    traits:
      - Reckless
      - Defiant
    points: 6
  - type: Heavy
    category: Cavalry
    melee:
      activation: 5
      to_hit_attacking: 4
      to_hit_defending: 5
    move:
      activation: 5
      Distance: 10
    fighting_strength:
      current: 6
      maximum: 6
    resolve: 4
    toughness: 3
    traits:
      - Defiant
    points: 4
  - type: Light
    category: Cavalry
    melee:
      activation: 7
      to_hit_attacking: 5
      to_hit_defending: 6
    move:
      activation: 5
      Distance: 12
    missile:
      activation: 6
      to_hit: 5
      range: 12
    fighting_strength:
      current: 6
      maximum: 6
    resolve: 5
    toughness: 3
    points: 4
  - type: Elite
    category: Engine
    melee:
      to_hit_defending: 5
    move:
      activation: 7
      Distance: 4
    missile:
      activation: 5
      to_hit: 4
      range: 24
    fighting_strength:
      current: 6
      maximum: 6
    resolve: 4
    toughness: 3
    traits:
      - Ponderous
    points: 6
  - type: Heavy
    category: Engine
    melee:
      to_hit_defending: 6
    move:
      activation: 8
      Distance: 2
    missile:
      activation: 6
      to_hit: 5
      range: 24
    fighting_strength:
      current: 6
      maximum: 6
    resolve: 5
    toughness: 2
    traits:
      - Ponderous
    points: 4
  - type: Light
    category: Engine
    melee:
      to_hit_defending: 6
    move:
      activation: 8
      Distance: 4
    missile:
      activation: 6
      to_hit: 5
      range: 18
    fighting_strength:
      current: 6
      maximum: 6
    resolve: 5
    toughness: 1
    points: 4
  - type: Elite
    category: Foot
    melee:
      activation: 5
      to_hit_attacking: 3
      to_hit_defending: 4
    move:
      activation: 5
      Distance: 6
    fighting_strength:
      current: 12
      maximum: 12
    resolve: 3
    toughness: 4
    points: 5
  - type: Heavy
    category: Foot
    melee:
      activation: 6
      to_hit_attacking: 5
      to_hit_defending: 4
    move:
      activation: 5
      Distance: 6
    fighting_strength:
      current: 12
      maximum: 12
    resolve: 4
    toughness: 3
    traits:
      - Defensive
    points: 4
  - type: Light
    category: Foot
    melee:
      activation: 6
      to_hit_attacking: 5
      to_hit_defending: 4
    move:
      activation: 5
      Distance: 8
    fighting_strength:
      current: 12
      maximum: 12
    resolve: 4
    toughness: 2
    traits:
      - Defensive
    points: 3
